### ISSUE TITLE
Cleanup CitA data

### ISSUE THREAD

**Issue by stevenwilkin** [guidance-guarantee-programme/locator#14]
We have 3 duplicate titles in the CitA data:

``` bash
$ grep title *json | sed 's/\",$//' | sed 's/.*\"//' | sort > 1.txt
$ grep title *json | sed 's/\",$//' | sed 's/.*\"//' | sort | uniq > 2.txt
$ diff 1.txt 2.txt
33d32
< Bedford & District CAB
136d134
< Citizens Advice Shropshire - Shrewsbury
249d246
< Hammersmith and Fulham Citizens Advice Bureau
$
```

`Bedford & District CAB` appears to be a straight-forward duplicate but the other 2 have different addresses.

**Comment by andrewgarner** [comment]
All duplicates have been addressed with the exception of "Dolgellau Citizens Advice" - we'll need to contact them directly to establish the correct details.

If we introduce slugs we'll need a way of differentiating "Bangor Citizens Advice" as there is a Bangor in both Ireland and Wales.
